Repository Student-Center/3days-oas, pull requests merged in 2024-09, with the labels that each got.

#2 ✨ 회원가입, 로그인 API 명세 작성
  openapi.yaml
Labels: feat

#3 [WEAV-25] 📝 토큰 재발급 API 명세
  openapi.yaml
Labels: docs

#5 [Enhance] Add location api
  openapi.yaml
Labels: docs

#8 [Enhance] Add company search api
  openapi.yaml
Labels: feat

#10 🩹 코드 생성시 에러 수정 및 validation gitaction 추가
  .github/workflows/validation.yaml
  openapi.yaml
Labels: fix
